version: "3.7"
services:
  nc_nextcloud:
    image: nextcloud:latest
    container_name: nc_nextcloud
    restart: always
    volumes:
      - /Nextcloud/nc_nextcloud/var/www/html/:/var/www/html/
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_HOST
      - NEXTCLOUD_ADMIN_USER
      - NEXTCLOUD_ADMIN_PASSWORD
      - NEXTCLOUD_TRUSTED_DOMAINS
      - REDIS_HOST
      - REDIS_HOST_PORT
      - OVERWRITEHOST
      - OVERWRITEPROTOCOL
      - default_phone_region
    depends_on:
      - nc_database
  nc_database:
    image: mysql
    container_name: nc_database
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    volumes:
      - /Nextcloud/nc_database/var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
  nc_redis:
    image: redis:alpine
    container_name: nc_redis
    restart: always
    volumes:
      - /Nextcloud/nc_redis/usr/local/etc/redis:/usr/local/etc/redis
      - /Nextcloud/nc_redis/data:/data
  nc_nginx:
    image: nginx
    container_name: nc_nginx
    restart: always
    volumes:
      - /Nextcloud/nc_nginx/etc/nginx:/etc/nginx
      - /Nextcloud/nc_nginx/etc/letsencrypt:/etc/letsencrypt
    environment:
      - DOMAIN_NAME
    ports:
      - "443:443"
      - "80:80"
  #nc_collabora:
  #  image: collabora/code
  #  container_name: nc_collabora
  #  restart: always
  #  environment:
  #    - DOMAIN
  #  expose:
  #    - "9980"
  #  cap_add:
  #    - MKNOD
